[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.20.2"
  NPM_VERSION = "8.19.4"
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions/api"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  NETLIFY_NODE_VERSION = "18.20.2"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

# Single Page Application (SPA) fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://*.netlify.app;"

# CORS for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-api-key, Authorization"
    Access-Control-Allow-Credentials = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "dist/public"